-- =============================================================================
-- Cairnquill: 00_setup.sql
-- Creates database, warehouse, resource monitor, roles and schemas.
-- Run as SYSADMIN (not ACCOUNTADMIN). Review grants before executing.
-- All data used is SYNTHETIC.
-- =============================================================================

-- Warehouse and resource monitor
CREATE WAREHOUSE IF NOT EXISTS CQ_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND   = 60
  AUTO_RESUME    = TRUE
  COMMENT        = 'Cairnquill compute – dev and app';

CREATE RESOURCE MONITOR IF NOT EXISTS CQ_RM
  WITH CREDIT_QUOTA = 20
  TRIGGERS
    ON 80 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE CQ_WH SET RESOURCE_MONITOR = CQ_RM;

-- Database
CREATE DATABASE IF NOT EXISTS CAIRNQUILL_DB
  COMMENT = 'Cairnquill AML STR copilot – SYNTHETIC data only';

-- Schemas
CREATE SCHEMA IF NOT EXISTS CAIRNQUILL_DB.RAW       COMMENT = 'Raw ingested data';
CREATE SCHEMA IF NOT EXISTS CAIRNQUILL_DB.GT        COMMENT = 'Ground-truth labels from AMLworld';
CREATE SCHEMA IF NOT EXISTS CAIRNQUILL_DB.FEATURES  COMMENT = 'Derived account features';
CREATE SCHEMA IF NOT EXISTS CAIRNQUILL_DB.CASES     COMMENT = 'Alert cases, drafts, verdicts';
CREATE SCHEMA IF NOT EXISTS CAIRNQUILL_DB.EVIDENCE  COMMENT = 'Immutable evidence snapshots';
CREATE SCHEMA IF NOT EXISTS CAIRNQUILL_DB.AUDIT     COMMENT = 'Append-only audit trail';
CREATE SCHEMA IF NOT EXISTS CAIRNQUILL_DB.EVAL      COMMENT = 'Evaluation runs and planted errors';
CREATE SCHEMA IF NOT EXISTS CAIRNQUILL_DB.REG       COMMENT = 'Regulatory text search';

-- Roles
CREATE ROLE IF NOT EXISTS CQ_DEV     COMMENT = 'Developers and CoCo CLI';
CREATE ROLE IF NOT EXISTS CQ_APP     COMMENT = 'API runtime – least privilege';
CREATE ROLE IF NOT EXISTS CQ_AUDITOR COMMENT = 'Read-only auditor – KYC masked';

-- Role hierarchy
GRANT ROLE CQ_APP     TO ROLE CQ_DEV;
GRANT ROLE CQ_AUDITOR TO ROLE CQ_DEV;

-- Warehouse grants
GRANT USAGE ON WAREHOUSE CQ_WH TO ROLE CQ_DEV;
GRANT USAGE ON WAREHOUSE CQ_WH TO ROLE CQ_APP;

-- Database grants
GRANT USAGE ON DATABASE CAIRNQUILL_DB TO ROLE CQ_DEV;
GRANT USAGE ON DATABASE CAIRNQUILL_DB TO ROLE CQ_APP;
GRANT USAGE ON DATABASE CAIRNQUILL_DB TO ROLE CQ_AUDITOR;

-- Schema grants – CQ_DEV gets all
GRANT ALL ON ALL SCHEMAS IN DATABASE CAIRNQUILL_DB TO ROLE CQ_DEV;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE CAIRNQUILL_DB TO ROLE CQ_DEV;

-- Schema grants – CQ_APP (runtime only)
GRANT USAGE ON SCHEMA CAIRNQUILL_DB.RAW       TO ROLE CQ_APP;
GRANT USAGE ON SCHEMA CAIRNQUILL_DB.GT        TO ROLE CQ_APP;
GRANT USAGE ON SCHEMA CAIRNQUILL_DB.FEATURES  TO ROLE CQ_APP;
GRANT USAGE ON SCHEMA CAIRNQUILL_DB.CASES     TO ROLE CQ_APP;
GRANT USAGE ON SCHEMA CAIRNQUILL_DB.EVIDENCE  TO ROLE CQ_APP;
GRANT USAGE ON SCHEMA CAIRNQUILL_DB.AUDIT     TO ROLE CQ_APP;
GRANT USAGE ON SCHEMA CAIRNQUILL_DB.EVAL      TO ROLE CQ_APP;
GRANT USAGE ON SCHEMA CAIRNQUILL_DB.REG       TO ROLE CQ_APP;

-- Table grants – CQ_APP
GRANT SELECT ON ALL TABLES IN SCHEMA CAIRNQUILL_DB.RAW      TO ROLE CQ_APP;
GRANT SELECT ON ALL TABLES IN SCHEMA CAIRNQUILL_DB.GT       TO ROLE CQ_APP;
GRANT SELECT ON ALL TABLES IN SCHEMA CAIRNQUILL_DB.FEATURES TO ROLE CQ_APP;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CAIRNQUILL_DB.RAW      TO ROLE CQ_APP;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CAIRNQUILL_DB.GT       TO ROLE CQ_APP;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CAIRNQUILL_DB.FEATURES TO ROLE CQ_APP;

GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA CAIRNQUILL_DB.CASES    TO ROLE CQ_APP;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA CAIRNQUILL_DB.EVIDENCE TO ROLE CQ_APP;
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA CAIRNQUILL_DB.CASES    TO ROLE CQ_APP;
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA CAIRNQUILL_DB.EVIDENCE TO ROLE CQ_APP;

-- Audit is append-only for the app role
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA CAIRNQUILL_DB.AUDIT TO ROLE CQ_APP;
GRANT SELECT, INSERT ON FUTURE TABLES IN SCHEMA CAIRNQUILL_DB.AUDIT TO ROLE CQ_APP;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA CAIRNQUILL_DB.EVAL TO ROLE CQ_APP;
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA CAIRNQUILL_DB.EVAL TO ROLE CQ_APP;
GRANT SELECT ON ALL TABLES IN SCHEMA CAIRNQUILL_DB.REG TO ROLE CQ_APP;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CAIRNQUILL_DB.REG TO ROLE CQ_APP;

-- Auditor grants
GRANT USAGE ON SCHEMA CAIRNQUILL_DB.AUDIT    TO ROLE CQ_AUDITOR;
GRANT USAGE ON SCHEMA CAIRNQUILL_DB.CASES    TO ROLE CQ_AUDITOR;
GRANT USAGE ON SCHEMA CAIRNQUILL_DB.EVIDENCE TO ROLE CQ_AUDITOR;
GRANT USAGE ON SCHEMA CAIRNQUILL_DB.EVAL     TO ROLE CQ_AUDITOR;
GRANT SELECT ON ALL TABLES IN SCHEMA CAIRNQUILL_DB.AUDIT    TO ROLE CQ_AUDITOR;
GRANT SELECT ON ALL TABLES IN SCHEMA CAIRNQUILL_DB.CASES    TO ROLE CQ_AUDITOR;
GRANT SELECT ON ALL TABLES IN SCHEMA CAIRNQUILL_DB.EVIDENCE TO ROLE CQ_AUDITOR;
GRANT SELECT ON ALL TABLES IN SCHEMA CAIRNQUILL_DB.EVAL     TO ROLE CQ_AUDITOR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CAIRNQUILL_DB.AUDIT    TO ROLE CQ_AUDITOR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CAIRNQUILL_DB.CASES    TO ROLE CQ_AUDITOR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CAIRNQUILL_DB.EVIDENCE TO ROLE CQ_AUDITOR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CAIRNQUILL_DB.EVAL     TO ROLE CQ_AUDITOR;

-- Cortex usage (adjust database role name for your account)
-- GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE CQ_DEV;
-- GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE CQ_APP;
